### ISSUE TITLE
Magics prevent plots rendering in notebook which is confusing

### ISSUE THREAD

**Issue by robmarkcole** [fstroth/icevision_dashboards#1]
Hi
It took me a little while to figure out it is necessary to comment out the magics below in order for the plots to render in the notebook, you might consider removing them?
```
#%%capture --no-stderr
dash = TrainValRecordsComparison(test_train_records, test_valid_records, test_class_map)
dash.show()
```

**Comment by fstroth** [comment]
Hey
I put them in place to avoid the output leaking into the repo. The output changes the file size by some MB. For example, the dashboard notebook is  38.6 KB without the output and 1.81 MB with the ouput. If the output changes due to new features or something else it would cause the repo to bloat very fast, which is something I would like to avoid. Therefore, I capture the output.
But I think it would be good to add an note to the readme file.
